### ISSUE TITLE
Task pane is not loaded in the latest code

### ISSUE THREAD

**Issue by techvenky** [OfficeDev/Word-Add-in-Content-Control-Binding#1]
Task pane is not loaded in the latest code

**Comment by jamescro** [comment]
I can reproduce this. I'll look into this problem some more and let you know what I discover.

**Comment by Rick-Kirkham** [comment]
Fixed this by setting **Start Action**, in the project properties in VS, to **Office Desktop Client** and setting **Start Document** to **New Word Document**. (It was the **CorporateBio.docx**.) You can then manually open the CorporateBio.docx and the task pane add-in is still there. I'll include these changes in a push that will also update the add-in to use add-in commands.
